### PR TITLE
gitignore Carthage/ directory

### PR DESCRIPTION
**Pull request by rickpasetto**
This avoids "dirtying" the local git repository by doing a build.

### CODE REVIEW

**Comment by ps2** [comment]
The main reason for using git as a cache for these was to speed up the build. Can you provide details about what we're doing instead to avoid waiting even longer for builds?

**Comment by rickpasetto** [comment]
I was hoping to switch to CircleCI, and have it's caching mechanism take
care of this.
If we stick with Travis, we may be able to use its caching mechanism,
although it is less sophisticated.

**Comment by ps2** [comment]
Ok, can you re post the review request when we have an acceptable solution?

**Comment by rickpasetto** [comment]
ok

**Pull request closed without merging**
