### PR TITLE
LOOP-3880 Compute expiration reminder relative to expiration time

### PR DESCRIPTION
**Pull request by ps2**
https://tidepool.atlassian.net/browse/LOOP-3880

### CODE REVIEW

**Review by rickpasetto — COMMENTED** [review]
Maybe I'm just not grokking it, but it isn't obvious to me how this fixes LOOP-3880.  Perhaps a quick comment in the PR description would help?  Also...unit tests?

**Comment by ps2** [comment]
It's a little complicated. The pod has its own internal clock, which can drift wrt the phone clock. Pod expiration (and expiration warnings) happens when the pod's clock reaches 72 hours. The user is oriented to the phone's clock, which is more reliable, so we always display dates according to the phone's time. This change makes it so the user selected time (which is already displayed accounting for the pod clock shift) is converted into an offset correctly for use in the `PodExpirationAlert` constructor which appears to throw when certain values are passed in.  

Some, but not all, values that are not even hour increments will cause the constructor to throw. The `round` in this change is to make sure we pass in even hour increments, and the change from using `activatedAt` to `podExpiresAt` is to make sure we're using the same datum for our calculations, in case the pod shift was actually more than 30m.

**Comment by rickpasetto** [comment]
Got it.  Seems worthy of some code comments and a unit test...just so developers coming along later can grok it (and not break it :) )..

**Comment by ps2** [comment]
Ready for review again; added a unit test for this, and made some additional improvements.

**Review by rickpasetto — APPROVED** [review]
LGTM! (Thanks for adding unit test)

**Pull request merged**
