### PR TITLE
Add built PodSDK dependencies

### PR DESCRIPTION
**Pull request by ps2**
Adding binaries for PodSDK framework dependencies.

### CODE REVIEW

**Review by darinkrauss — COMMENTED** [review]
How will the included LoopKit based frameworks (LoopKit, LoopKitUI, LoopTestingKit, MockKit, MockKitUI, LoopKIt-watchOS) interact with the LoopKit in the LoopWorkspace?

**Comment by ps2** [comment]
Those frameworks are only used when building/testing standalone. They are not copied into the actual plugin.

**Comment by darinkrauss** [comment]
So there will be targets for a workspace build and targets for a standalone build?

**Comment by ps2** [comment]
No. Building standalone uses the same targets. The plugin target does not include LoopKit when copies dependency frameworks into place, as the plugin doesn't need them. (All Loop plugins do not provide LoopKit, as it is provided by Loop).

**Review by darinkrauss — APPROVED** [review]
LGTM. 🚢

**Pull request merged**
